### ISSUE TITLE
Exporting meshs never import as Skinned and can't be animated.

### ISSUE THREAD

**Issue by wallaby3** [apsislabs/blender_preflight#5]
I have no idea why, but I think it must be something to do with how the groups are organized. If I export a character, for example, the rig is exported but the character model is always set as a Mesh in Unity. Never a Skinned Mesh. It doesn't look like the weights carry over?

Manually selecting the character exports properly if I go through the Blender dialog.

I looked through the code for a few hours and nothing I try makes any difference. No idea.

**Comment by wkirby** [comment]
Interesting. What version of Blender are you using? I haven't touched this code since the update to 2.8, so I wouldn't be surprised if there's a problem.

If you don't mind, can you also send me your `.blend` file?

**Comment by wallaby3** [comment]
I'm using 2.79. I tried removing applying transforms and bake_space_transform which were marked as Experimental and possible to kill armatures and animations but nothing seemed to work. Finally, I changed the version to 'ASCII6100' and it imported properly. I'm not sure if this is a Unity or Blender issue with the later FBX version. I don't think there's anything wrong with the Add-on specifically.

**Comment by wkirby** [comment]
@wallaby3 Cooooool. Don't hesitate to reopen this issue if it turns out there is something weird with the plugin.

**Comment by wallaby3** [comment]
I think this plugin is excellent. Well written. If I knew Python and the Blender environment better, I'd try and help. I guess the main issue is having to use ASCII6100 instead of the later version. But only changing that one aspect has everything import properly. Not sure if there is any benefit to using a later FBX version.
